name = "Album"
description = "相册"

[[meta.permissions]]
scope = "hoshikuzu:album:view"
title = "相册查看"

[[meta.permissions]]
scope = "hoshikuzu:album:create"
title = "相册创建"

[[meta.permissions]]
scope = "hoshikuzu:album:update"
title = "相册更新"

[[meta.permissions]]
scope = "hoshikuzu:album:delete"
title = "相册删除"