name = "Post"
description = "文章"

[[meta.permissions]]
scope = "hoshikuzu:post:view"
title = "文章阅读"

[[meta.permissions]]
scope = "hoshikuzu:post:create"
title = "文章创建"

[[meta.permissions]]
scope = "hoshikuzu:post:update"
title = "文章更新"

[[meta.permissions]]
scope = "hoshikuzu:post:delete"
title = "文章删除"