name = "Role"
description = "角色"

[[meta.permissions]]
scope = "hoshikuzu:role:view"
title = "角色查看"

[[meta.permissions]]
scope = "hoshikuzu:role:create"
title = "角色创建"

[[meta.permissions]]
scope = "hoshikuzu:role:update"
title = "角色更新"

[[meta.permissions]]
scope = "hoshikuzu:role:delete"
title = "角色删除"