name = "Post"
description = "用户"

[[meta.permissions]]
scope = "hoshikuzu:user:view"
title = "用户阅读"

[[meta.permissions]]
scope = "hoshikuzu:user:create"
title = "用户创建"

[[meta.permissions]]
scope = "hoshikuzu:user:update"
title = "用户更新"

[[meta.permissions]]
scope = "hoshikuzu:user:delete"
title = "用户删除"